CYBERRU-322 split DotaMatchSummary into multiple structures
AbiosGaming/go-sdk-v2 pull request #16
Opened 2020-10-12 09:22 UTC by kurenkoff

2020-10-12 14:06 UTC, patstrom requested changes
Thank you for your PR! And thank you for fixing all the typos of "structure" that was in the old version. Something must've gone terribly wrong when auto-generating those.

Just a few typos and copy-paste errors to fix and I'm happy about this.

2020-10-12 14:06 UTC, patstrom commented on structs/dota_match_summary.go
> +// RoshanEvent is a summarization of data about Roshan event of Dota match.
This seems to be the documentation for the RoshanEvent struct

2020-10-12 14:06 UTC, patstrom commented on structs/dota_match_summary.go
> +	StricturePos  string `json:"structure_pos"`
`StricturePos` should probably be `StructurePos`.

2020-10-12 16:47 UTC, kurenkoff commented on structs/dota_match_summary.go
> +// RoshanEvent is a summarization of data about Roshan event of Dota match.
Ye, funny cope-paste error

2020-10-12 16:50 UTC, kurenkoff commented
@patstrom Hey, thank you for your feedback. I've fixed errors and also added some fields which are declared in API Reference but not presented in go code (networth, camps_staked, wards and runes)

2020-10-13 07:49 UTC, patstrom approved these changes
Thank you for your contribution!

2020-10-13 07:50 UTC, merged